-- MySQL Script generated by MySQL Workbench
-- lun 31 déc 2018 14:49:39 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tuto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tuto` ;

-- -----------------------------------------------------
-- Schema tuto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tuto` DEFAULT CHARACTER SET utf8 ;
USE `tuto` ;

-- -----------------------------------------------------
-- Table `tuto`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuto`.`users` ;

CREATE TABLE IF NOT EXISTS `tuto`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tuto`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuto`.`posts` ;

CREATE TABLE IF NOT EXISTS `tuto`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `content` VARCHAR(45) NULL,
  `create` DATETIME NULL,
  `online` INT NULL,
  `type` VARCHAR(255) NULL,
  `slug` VARCHAR(45) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tuto`.`configs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuto`.`configs` ;

CREATE TABLE IF NOT EXISTS `tuto`.`configs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `name_UNIQUE` ON `tuto`.`configs` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tuto`.`medias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuto`.`medias` ;

CREATE TABLE IF NOT EXISTS `tuto`.`medias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `file` VARCHAR(255) NULL,
  `post_id` INT NULL COMMENT '		',
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
